# Generated by Django 5.1.2 on 2024-10-12 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='patients',
            table='score1',
        ),
    ]
