# Generated by Django 5.1.2 on 2024-10-13 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp1', '0002_alter_patients_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='patients',
            table='public.score1',
        ),
    ]
